<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ApTutor.Tracer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApTutor.Scene\ApTutor.Scene.csproj" />
  </ItemGroup>

</Project>
